---
# tasks file for docker
- name: create image docker
  docker_image:
    name: devops
    build: 
     dest: "/var/lib/jenkins/workspace/devops"
     pull: no
    state: present
    force_source: true

